<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- This will include all the contents of example_include.xacro first. Go check it out! -->
    <xacro:include filename="example_include.xacro" />

    <!-- Load spherical robot geometric parameters: -->
    <xacro:arg name="r_b" default="1.0" />
    <xacro:arg name="ratio_c_b" default="1.0" />
    <xacro:arg name="ratio_e_b" default="1.0" />
    <!-- Convert them into xacro properties: -->
    <xacro:property name="r_b" value="$(arg r_b)" />
    <xacro:property name="ratio_c_b" value="$(arg ratio_c_b)" />
    <xacro:property name="ratio_e_b" value="$(arg ratio_e_b)" />

    <xacro:property name="arm_length" value="1" />
    <xacro:property name="arm_radius" value="0.1" />


    
    <!-- world -->
    <link name="world"></link>


    <!-- world to base -->
    <joint name="joint_world_base" type="fixed">
        <origin xyz="${4 * r_b} 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base"/>        
    </joint>


    <!-- base -->
    <link name="base"></link>


    <!-- base to rot_cen -->
    <joint name="joint_base_rot_cen" type="fixed">
        <origin xyz="0 0 ${ratio_c_b * r_b}" rpy="0 0 0"/>
        <parent link="base"/>
        <child link="rot_cen"/>        
    </joint>


    <!-- rot_cen -->
    <link name="rot_cen"></link>


    <!-- rot_cen to motor 0 -->
    <joint name="joint_0" type="revolute">
        <parent link="rot_cen"/>
        <child link="motor_0"/>

        <origin xyz="0.5 0 -0.1665" rpy="-1.24935 -0 1.5708"/>
        <axis xyz="0 0 1"/>

        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/> 
    </joint>

    
    <link name="motor_0">
        <visual>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- rot_cen to motor 1 -->
    <joint name="joint_1" type="revolute">
        <parent link="rot_cen"/>
        <child link="motor_1"/>

        <origin xyz="-0.25 0.433013 -0.1665" rpy="-1.24935 -1.66282e-09 -2.61799"/>
        <axis xyz="0 0 1"/>

        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/> 
    </joint>

    <link name="motor_1">
        <!-- <visual>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder> -->
    </link>


    <!-- rot_cen to motor 2 -->
    <joint name="joint_2" type="revolute">
        <parent link="rot_cen"/>
        <child link="motor_2"/>

        <origin xyz="-0.25 -0.433013   -0.1665" rpy="-1.24935 -6.45836e-08 -0.523599"/>
        <axis xyz="0 0 1"/>

        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/> 
    </joint>

    <link name="motor_2">
        <!-- <visual>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder> -->
    </link>

</robot>
